.SUFFIXES:

CURRENT_PATH := $(realpath $(dir $(lastword $(MAKEFILE_LIST))))

IGNORES := .git .DS_Store .gitignore .gitmodules %.swp

DOTFILES := $(filter-out $(IGNORES), $(wildcard .??*))

.PHONY: default
default: build

.PHONY: all
all: install

.PHONY: install
install: deploy

.PHONY: deploy
deploy: build
	@$(foreach val, $(DOTFILES), ln -sfnv $(abspath $(val)) $(HOME)/$(val);)
	fc-scan .fonts
	fc-cache -vf

.PHONY: build
build: update .zsh/ls_colors.zsh .fonts

.PHONY: update
update:
	git submodule update --init

.PHONY: clean
clean:
	@-$(foreach val, $(DOTFILES), rm -vrf $(HOME)/$(val);)

.zsh/ls_colors.zsh: src/dircolors
	@echo '# This file was generated by dircolors from src/dircolors. Do not edit this file directly!!' > $@
	dircolors $< >> $@


.fonts:
	mkdir -p $@
	curl -sL https://github.com/miiton/Cica/releases/download/v4.1.1/Cica-v4.1.1.zip > Cica.zip
	unzip Cica.zip -d .fonts
	rm Cica.zip
